# Generated by Django 3.2.25 on 2024-10-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20240925_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=50)),
                ('packageName', models.CharField(blank=True, default='-', max_length=150, null=True)),
                ('componentName', models.CharField(blank=True, default='-', max_length=150, null=True)),
                ('nodeViewId', models.CharField(blank=True, default='-', max_length=150, null=True)),
                ('nodeAddress', models.CharField(blank=True, default='-', max_length=150, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('detail', models.TextField(blank=True, default='-', null=True)),
            ],
        ),
    ]
