name: Deploy to EC2

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH and Deploy
      run: |
        # .sshディレクトリを作成
        mkdir -p ~/.ssh
        # GitHub Secretsに保存した秘密鍵をそのまま使う
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        # 適切なパーミッションを設定
        chmod 600 ~/.ssh/id_rsa

        # SSH接続してEC2上でコマンドを実行
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -tt ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/manualToolSample  # あなたのアプリのパスに変更
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          sudo systemctl restart gunicorn  # アプリケーションサーバーを再起動
        EOF





