name: Deploy to EC2

on:
  push:
    branches:
      - main  # mainブランチにプッシュした時に実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and Deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        # 秘密鍵を一時ファイルに保存
        echo "$SSH_PRIVATE_KEY" > temp_key.pem
        chmod 600 temp_key.pem

        # SSH接続してEC2上でデプロイ
        ssh -o StrictHostKeyChecking=no -i temp_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          cd /home/ubuntu/manualToolSample
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          sudo systemctl restart gunicorn
        EOF

        # 一時鍵ファイルの削除
        rm temp_key.pem
