name: Deploy to EC2

on:
  push:
    branches:
      - main  # mainブランチにプッシュした時に実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and Deploy
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no -i /home/ubuntu/manualToolSample/ubuntu20241012.pem $EC2_USER@$EC2_HOST << 'EOF'
          cd /home/ubuntu/manualToolSample
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          sudo systemctl restart gunicorn
        EOF



