name: Deploy to EC2

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_PASSWORD: ${{ secrets.EC2_PASSWORD }}
      run: |
        sshpass -p $EC2_PASSWORD ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -tt $EC2_USER@$EC2_HOST << 'EOF'
          cd /home/ubuntu/manualToolSample
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          sudo systemctl restart gunicorn
        EOF






